lint-fix-web:
    docker exec -it react_frontend_web npm run lint:fix

lint-fix-admin:
	docker exec -it react_frontend_admin npm run lint:fix

lint-fix-ecoponto:
    docker exec -it react_frontend_ecoponto npm run lint:fix

lint-fix-all: lint-fix-web lint-fix-admin lint-fix-ecoponto