from core.domain.entities import *
from collections import defaultdict
from datetime import timedelta
from django.core.management.base import BaseCommand
from django.core.files.base import ContentFile
from django.db import transaction as django_transaction
from django.utils import timezone
from faker import Faker
import logging
import random
import requests
import csv
import os

from core.domain.models import *

# Logging basic configuration
logger = logging.getLogger(__name__)

# Initializes Faker, defining brazilian language
fake = Faker('pt_BR')

def load_recycling_points_from_csv_with_managers(manager_users):
    """
    Load RecyclingPoints from CSV file and associate with manager users.
    The first column (maps_id) is the Google Maps identifier.
    The recycling_point_id is auto-generated by the database.
    """
    logger.info("Loading RecyclingPoints from CSV and associating with managers...")
    
    # Get the path to the CSV file (same directory as manage.py)
    csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))), 'RECYCLING_POINT.csv')
    
    if not os.path.exists(csv_path):
        logger.error(f"CSV file not found at {csv_path}")
        return
    
    if not manager_users:
        logger.error("No manager users provided. Aborting recycling points creation.")
        return
    
    try:
        recycling_points_to_create = []
        created_count = 0
        skipped_count = 0
        manager_index = 0
        
        with open(csv_path, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                try:
                    maps_id = row.get('maps_id', '').strip('"')
                    name = row.get('name', '').strip('"')
                    cnpj = row.get('cnpj', '').strip('"')
                    zip_code = row.get('zip_code', '').strip('"')
                    latitude = float(row.get('latitude', '0').strip('"'))
                    longitude = float(row.get('longitude', '0').strip('"'))
                    address = row.get('address', '').strip('"')
                    
                    # Validate required fields
                    if not all([maps_id, name, latitude, longitude]):
                        logger.warning(f"Skipping row with missing required fields: {row}")
                        skipped_count += 1
                        continue
                    
                    # Check if already exists by maps_id
                    if RecyclingPoint.objects.filter(maps_id=maps_id).exists():
                        logger.info(f"RecyclingPoint already exists: {name}")
                        skipped_count += 1
                        continue
                    
                    # Assign manager user using round-robin distribution
                    assigned_manager = manager_users[manager_index % len(manager_users)]
                    manager_index += 1
                    
                    # Create RecyclingPoint object
                    # recycling_point_id will be auto-generated
                    recycling_point = RecyclingPoint(
                        maps_id=maps_id,
                        name=name,
                        cnpj=cnpj,
                        zip_code=zip_code,
                        latitude=latitude,
                        longitude=longitude,
                        address=address,
                        user_id=assigned_manager  # Associate with manager user
                    )

                    
                    recycling_points_to_create.append(recycling_point)
                    created_count += 1
                    
                except ValueError as e:
                    logger.error(f"Error parsing row: {row}. Error: {str(e)}")
                    skipped_count += 1
                    continue
        
        # Bulk create all RecyclingPoints
        if recycling_points_to_create:
            RecyclingPoint.objects.bulk_create(recycling_points_to_create, ignore_conflicts=True)
        
        logger.info(f"CSV Import Summary: Created={created_count}, Skipped={skipped_count}")
        
    except Exception as e:
        logger.error(f"An error occurred while loading RecyclingPoints from CSV: {e}")

def load_users_from_csv():
    """
    Load users from USER.csv and create Wallet for each user.
    The CSV should have columns: username, first_name, last_name, email, cpf, zip_code, password, ACCESS_LEVEL
    """
    logger.info("Loading Users from CSV...")
    
    # Get the path to the CSV file (same directory as manage.py)
    csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))), 'USER.csv')
    
    if not os.path.exists(csv_path):
        logger.error(f"CSV file not found at {csv_path}")
        return []
    
    try:
        users_to_create = []
        wallets_to_create = []
        created_count = 0
        skipped_count = 0
        
        with open(csv_path, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                try:
                    username = row.get('username', '').strip('"').strip()
                    first_name = row.get('first_name', '').strip('"').strip()
                    last_name = row.get('last_name', '').strip('"').strip()
                    email = row.get('email', '').strip('"').strip()
                    cpf = row.get('cpf', '').strip('"').strip()
                    zip_code = row.get('zip_code', '').strip('"').strip()
                    password = row.get('password', '').strip('"').strip()
                    access_level = row.get('ACCESS_LEVEL', 'U').strip('"').strip()
                    
                    # Validate required fields
                    if not username:
                        logger.warning(f"Skipping row with missing username: {row}")
                        skipped_count += 1
                        continue
                    
                    # Check if already exists by username
                    if User.objects.filter(username=username).exists():
                        logger.info(f"User already exists: {username}")
                        skipped_count += 1
                        continue
                    
                    # Create User object
                    user = User(
                        username=username,
                        first_name=first_name,
                        last_name=last_name,
                        email=email,
                        cpf=cpf,
                        zip_code=zip_code,
                        password=password,  # Use hashed password from CSV
                        access_level=access_level,
                        is_active=True
                    )
                    
                    users_to_create.append(user)
                    created_count += 1
                    
                except Exception as e:
                    logger.error(f"Error parsing row: {row}. Error: {str(e)}")
                    skipped_count += 1
                    continue
        
        # Bulk create all Users
        if users_to_create:
            created_users = User.objects.bulk_create(users_to_create)
            
            # Create Wallet for each created user
            for user in created_users:
                wallets_to_create.append(
                    Wallet(user_id=user, points_balance=0)
                )
            
            if wallets_to_create:
                created_wallets = Wallet.objects.bulk_create(wallets_to_create)
        
        logger.info(f"CSV Import Summary: Created Users={created_count}, Skipped={skipped_count}")
        return created_users if users_to_create else []
        
    except Exception as e:
        logger.error(f"An error occurred while loading Users from CSV: {e}")
        return []

def load_recyclings_from_csv():
    """
    Load recyclings from RECYCLING.csv and create them in the database.
    If user_id is a number, associate with that User; if NULL, don't associate with any user.
    """
    logger.info("Loading Recyclings from CSV...")
    
    # Get the path to the CSV file (same directory as manage.py)
    csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))), 'RECYCLING.csv')
    
    if not os.path.exists(csv_path):
        logger.error(f"CSV file not found at {csv_path}")
        return []
    
    try:
        recyclings_to_create = []
        created_count = 0
        skipped_count = 0
        
        with open(csv_path, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                try:
                    points_value = int(row.get('points_value', '0').strip('"'))
                    weight = float(row.get('weight', '0').strip('"'))
                    date_str = row.get('date', '').strip('"')
                    validation_hash = row.get('validation_hash', '').strip('"')
                    status = row.get('STATUS', 'ACTIVE').strip('"')
                    user_id_str = row.get('user_id', '').strip('"').strip()
                    recycling_point_id_str = row.get('RECYCLING_POINT_ID', '').strip('"')
                    recycling_value_id_str = row.get('RECYCLING_VALUE_ID', '').strip('"')
                    
                    # Validate required fields
                    if not all([points_value, weight, validation_hash, recycling_point_id_str, recycling_value_id_str]):
                        logger.warning(f"Skipping row with missing required fields: {row}")
                        skipped_count += 1
                        continue
                    
                    # Parse user_id: if it's a number, associate; if NULL or empty, don't associate
                    user_id = None
                    if user_id_str and user_id_str.upper() != 'NULL':
                        try:
                            user_id_int = int(user_id_str)
                            # Check if user exists
                            try:
                                user_id = User.objects.get(user_id=user_id_int)
                            except User.DoesNotExist:
                                logger.warning(f"User with id {user_id_int} not found, skipping recycling")
                                skipped_count += 1
                                continue
                        except ValueError:
                            logger.warning(f"Invalid user_id format: {user_id_str}, skipping recycling")
                            skipped_count += 1
                            continue
                    
                    # Get RecyclingPoint
                    try:
                        recycling_point_id = RecyclingPoint.objects.get(recycling_point_id=int(recycling_point_id_str))
                    except RecyclingPoint.DoesNotExist:
                        logger.warning(f"RecyclingPoint with id {recycling_point_id_str} not found, skipping recycling")
                        skipped_count += 1
                        continue
                    
                    # Get RecyclingValue
                    try:
                        recycling_value_id = RecyclingValue.objects.get(recycling_value_id=int(recycling_value_id_str))
                    except RecyclingValue.DoesNotExist:
                        logger.warning(f"RecyclingValue with id {recycling_value_id_str} not found, skipping recycling")
                        skipped_count += 1
                        continue
                    
                    # Parse date if provided
                    date = None
                    if date_str:
                        try:
                            # Try to parse ISO format date
                            from django.utils.dateparse import parse_datetime
                            date = parse_datetime(date_str)
                            if date is None:
                                date = timezone.now()
                        except Exception as e:
                            logger.warning(f"Could not parse date {date_str}, using current time: {e}")
                            date = timezone.now()
                    else:
                        date = timezone.now()
                    
                    # Create Recycling object
                    recycling = Recycling(
                        user_id=user_id,
                        recycling_point_id=recycling_point_id,
                        recycling_value_id=recycling_value_id,
                        points_value=points_value,
                        weight=weight,
                        date=date,
                        validation_hash=validation_hash,
                        status=status
                    )
                    
                    recyclings_to_create.append(recycling)
                    created_count += 1
                    
                except Exception as e:
                    logger.error(f"Error parsing row: {row}. Error: {str(e)}")
                    skipped_count += 1
                    continue
        
        # Bulk create all Recyclings
        if recyclings_to_create:
            created_recyclings = Recycling.objects.bulk_create(recyclings_to_create, ignore_conflicts=True)
        
        logger.info(f"CSV Import Summary: Created Recyclings={created_count}, Skipped={skipped_count}")
        return recyclings_to_create if recyclings_to_create else []
        
    except Exception as e:
        logger.error(f"An error occurred while loading Recyclings from CSV: {e}")
        return []

def load_blog_posts_from_csv():
    """
    Load blog posts from POST_BLOG.csv and create them in the database.
    For each post, also create a PostImage with a placeholder image.
    """
    logger.info("Loading Blog Posts from CSV...")
    
    csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))), 'POST_BLOG.csv')
    
    if not os.path.exists(csv_path):
        logger.error(f"CSV file not found at {csv_path}")
        return {}
    
    try:
        posts_to_create = []
        created_posts = {}
        created_count = 0
        skipped_count = 0
        
        with open(csv_path, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                try:
                    post_id = row.get('post_id', '').strip('"')
                    title = row.get('title', '').strip('"')
                    text = row.get('text', '').strip('"')
                    created_at_str = row.get('created_at', '').strip('"')
                    last_edition_date_str = row.get('last_edition_date', '').strip('"')
                    author_id_str = row.get('AUTHOR_ID', '').strip('"')
                    
                    # Validate required fields
                    if not all([post_id, title, text, author_id_str]):
                        logger.warning(f"Skipping row with missing required fields: {row}")
                        skipped_count += 1
                        continue
                    
                    # Check if post already exists
                    if PostBlog.objects.filter(post_id=int(post_id)).exists():
                        logger.info(f"PostBlog already exists: {title}")
                        skipped_count += 1
                        continue
                    
                    # Get author user
                    try:
                        author = User.objects.get(user_id=int(author_id_str))
                    except User.DoesNotExist:
                        logger.warning(f"Author with id {author_id_str} not found, skipping post")
                        skipped_count += 1
                        continue
                    
                    # Parse dates if provided
                    created_at = None
                    if created_at_str:
                        try:
                            from django.utils.dateparse import parse_datetime
                            created_at = parse_datetime(created_at_str)
                            if created_at is None:
                                created_at = timezone.now()
                        except Exception as e:
                            logger.warning(f"Could not parse created_at {created_at_str}: {e}")
                            created_at = timezone.now()
                    else:
                        created_at = timezone.now()
                    
                    last_edition_date = None
                    if last_edition_date_str:
                        try:
                            from django.utils.dateparse import parse_datetime
                            last_edition_date = parse_datetime(last_edition_date_str)
                            if last_edition_date is None:
                                last_edition_date = timezone.now()
                        except Exception as e:
                            logger.warning(f"Could not parse last_edition_date {last_edition_date_str}: {e}")
                            last_edition_date = timezone.now()
                    else:
                        last_edition_date = timezone.now()
                    
                    # Create PostBlog object
                    post = PostBlog(
                        post_id=int(post_id),
                        author_id=author,
                        title=title,
                        text=text,
                        created_at=created_at,
                        last_edition_date=last_edition_date
                    )
                    
                    posts_to_create.append(post)
                    created_posts[int(post_id)] = post
                    created_count += 1
                    
                except Exception as e:
                    logger.error(f"Error parsing row: {row}. Error: {str(e)}")
                    skipped_count += 1
                    continue
        
        # Bulk create all PostBlogs
        if posts_to_create:
            PostBlog.objects.bulk_create(posts_to_create)
            
            # Create PostImage for each post with placeholder image
            logger.info("Creating PostImages with placeholder image...")
            image_url = "https://placehold.co/800x400/22c55e/ffffff.png?text=Recicash+Blog"
            images_to_create = []
            
            try:
                response = requests.get(image_url, timeout=10)
                if response.status_code == 200:
                    for post in posts_to_create:
                        try:
                            image_name = f"blog_post_{post.post_id}.png"
                            image_file = ContentFile(response.content, name=image_name)
                            
                            image = PostImage(post=post)
                            image.image.save(image_name, image_file, save=False)
                            images_to_create.append(image)
                        except Exception as e:
                            logger.error(f"Error creating image for post {post.post_id}: {e}")
                    
                    if images_to_create:
                        PostImage.objects.bulk_create(images_to_create)
                        logger.info(f"PostImages created successfully: {len(images_to_create)} images")
                else:
                    logger.warning(f"Failed to download placeholder image. Status code: {response.status_code}")
            except Exception as e:
                logger.error(f"Error downloading or creating placeholder images: {e}")
        
        logger.info(f"CSV Import Summary: Created PostBlogs={created_count}, Skipped={skipped_count}")
        return created_posts
        
    except Exception as e:
        logger.error(f"An error occurred while loading PostBlogs from CSV: {e}")
        return {}

def load_post_images_from_csv(posts_dict):
    """
    Load post images from POST_IMAGE.csv and create them in the database.
    posts_dict should be a mapping of post_id to PostBlog objects.
    Images are loaded from the media/blog_images folder.
    """
    logger.info("Loading Post Images from CSV...")
    
    csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))), 'POST_IMAGE.csv')
    media_base_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))), 'media')
    
    if not os.path.exists(csv_path):
        logger.error(f"CSV file not found at {csv_path}")
        return []
    
    try:
        images_to_create = []
        created_count = 0
        skipped_count = 0
        
        with open(csv_path, 'r', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                try:
                    image_id = row.get('id', '').strip('"')
                    image_path = row.get('image', '').strip('"')
                    post_id_str = row.get('post_id', '').strip('"')
                    
                    # Validate required fields
                    if not all([image_id, image_path, post_id_str]):
                        logger.warning(f"Skipping row with missing required fields: {row}")
                        skipped_count += 1
                        continue
                    
                    # Get the post
                    post_id = int(post_id_str)
                    if post_id not in posts_dict:
                        # Try to fetch from database
                        try:
                            post = PostBlog.objects.get(post_id=post_id)
                        except PostBlog.DoesNotExist:
                            logger.warning(f"PostBlog with id {post_id} not found, skipping image")
                            skipped_count += 1
                            continue
                    else:
                        post = posts_dict[post_id]
                    
                    # Check if image already exists
                    if PostImage.objects.filter(id=int(image_id)).exists():
                        logger.info(f"PostImage already exists: {image_path}")
                        skipped_count += 1
                        continue
                    
                    # Construct full path to image file
                    full_image_path = os.path.join(media_base_path, image_path)
                    
                    # Check if image file exists
                    if not os.path.exists(full_image_path):
                        logger.warning(f"Image file not found at {full_image_path}, skipping image")
                        skipped_count += 1
                        continue
                    
                    # Read image file and create PostImage with actual file
                    try:
                        with open(full_image_path, 'rb') as img_file:
                            image_content = img_file.read()
                            image_name = os.path.basename(image_path)
                            image_file = ContentFile(image_content, name=image_name)
                            
                            image = PostImage(
                                id=int(image_id),
                                post=post
                            )
                            image.image.save(image_name, image_file, save=False)
                            images_to_create.append(image)
                            created_count += 1
                    except Exception as e:
                        logger.error(f"Error reading/saving image file {full_image_path}: {e}")
                        skipped_count += 1
                        continue
                    
                except Exception as e:
                    logger.error(f"Error parsing row: {row}. Error: {str(e)}")
                    skipped_count += 1
                    continue
        
        # Bulk create all PostImages
        if images_to_create:
            PostImage.objects.bulk_create(images_to_create)
        
        logger.info(f"CSV Import Summary: Created PostImages={created_count}, Skipped={skipped_count}")
        return images_to_create
        
    except Exception as e:
        logger.error(f"An error occurred while loading PostImages from CSV: {e}")
        return []

def create_data(number_of_users=10):
    
    logger.info("Starting initial data creation")

    # Get the current timezone from Django settings to make datetimes timezone-aware
    tz = timezone.get_current_timezone()

    wallet_history_to_create = []

    # Load Users from CSV
    logger.info("Loading users from USER.csv...")
    csv_users = load_users_from_csv()
    logger.info(f"Loaded {len(csv_users)} users from CSV")

    # Create Recycling Point Managers
    logger.info('Creating Recycling Point Managers...')
    managers_to_insert = []
    
    try:
        for i in range(1, 11):
            manager_full_name = fake.name()
            name_parts = manager_full_name.split()
            first_name = name_parts[0]
            last_name = ' '.join(name_parts[1:]) if len(name_parts) > 1 else ''
            
            cpf = fake.cpf()
            username = f'manager_{i}'
            email = f'{username}@recicash.fake'
            zip_code = fake.postcode()
            
            manager = User(
                username=username,
                first_name=first_name,
                last_name=last_name,
                email=email,
                cpf=cpf,
                zip_code=zip_code,
                access_level='M'  # Recycling Point Manager
            )
            manager.set_password('senha123')
            managers_to_insert.append(manager)
        
        created_managers = User.objects.bulk_create(managers_to_insert)
        logger.info(f"Managers created successfully: {len(created_managers)} managers")
    
    except Exception as e:
        logger.error(f"An error occurred while creating managers: {e}")
        created_managers = []
    
    # Load RecyclingPoints from CSV and associate with managers
    logger.info("Loading RecyclingPoints from CSV and associating with managers...")
    if created_managers:
        load_recycling_points_from_csv_with_managers(created_managers)
    else:
        logger.error("No managers created. Skipping recycling points association.")

    # Create Recycling Value
    logger.info(f"Creating Recycling value...")
    try:
        recycling_value, created = RecyclingValue.objects.get_or_create(
            points_value=500.0,
            defaults={'date': timezone.now() - timedelta(days=366)}
        )
        if created:
            logger.info(f"Recycling value created successfully")
        else:
            logger.info(f"Recycling value already exists")
    except Exception as e:
        logger.error(f"An unexpected error occurred while creating Recycling Value: {e}")
        return
    
    # Load Recyclings from CSV
    logger.info("Loading recyclings from RECYCLING.csv...")
    csv_recyclings = load_recyclings_from_csv()
    logger.info(f"Loaded {len(csv_recyclings)} recyclings from CSV")
    
    # Add WalletHistory for recyclings with associated users
    for recycling in csv_recyclings:
        if recycling.user_id:  # Only if recycling has an associated user
            wallet_history_to_create.append(
                WalletHistory(
                    user_id=recycling.user_id,
                    operation='RECYCLING',
                    value=recycling.points_value,
                    date=recycling.date
                )
            )

    # Load Blog Posts from CSV
    logger.info("Loading blog posts from POST_BLOG.csv...")
    csv_posts = load_blog_posts_from_csv()
    logger.info(f"Loaded {len(csv_posts)} blog posts from CSV")

    # Create WalletHistory
    logger.info("Creating Wallet History records...")
    if not wallet_history_to_create:
        logger.warning("No history items to create. Skipping.")
    else:
        try:
            created_history = WalletHistory.objects.bulk_create(wallet_history_to_create)
            logger.info(f"Wallet history records created successfully: {len(created_history)} records")
        except Exception as e:
            logger.error(f"An unexpected error occurred while creating wallet history: {e}")

    # Create Wallets
    logger.info("Calculating final balances and creating wallets for all users...")
    try:
        user_balances = defaultdict(int)
        for history_item in wallet_history_to_create:
            user_balances[history_item.user_id] += history_item.value

        wallets_to_create = []
        all_system_users = User.objects.all()

        for user in all_system_users:
            balance = user_balances.get(user, 0)
            # Ensure balance is never negative
            if balance < 0:
                balance = 0
                logger.warning(f"User {user.username} had negative balance, setting to 0")
            
            wallets_to_create.append(
                Wallet(user_id=user, points_balance=balance)
            )
        
        Wallet.objects.all().delete()
        created_wallets = Wallet.objects.bulk_create(wallets_to_create)
        logger.info(f"Wallets created successfully: {len(created_wallets)} wallets")

    except Exception as e:
        logger.error(f"An unexpected error occurred while creating wallets: {e}")

    logger.info("="*60)
    logger.info("Initial data creation completed successfully!")
    logger.info(f"Summary:")
    logger.info(f"  - Users: {User.objects.count()}")
    logger.info(f"  - Managers: {User.objects.filter(access_level='M').count()}")
    logger.info(f"  - Recycling Points: {RecyclingPoint.objects.count()}")
    logger.info(f"  - Recyclings: {Recycling.objects.count()}")
    logger.info(f"  - Partner Companies: {PartnerCompany.objects.count()}")
    logger.info(f"  - Coupons: {Coupon.objects.count()}")
    logger.info(f"  - Coupon Transactions: {CouponsTransactions.objects.count()}")
    logger.info(f"  - Wallet History: {WalletHistory.objects.count()}")
    logger.info(f"  - Blog Posts: {PostBlog.objects.count()}")
    logger.info(f"  - Wallets: {Wallet.objects.count()}")
    logger.info("="*60)


class Command(BaseCommand):
    help = 'Populates the database with initial, necessary data for the application to run.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--total', 
            type=int, 
            default=10, 
            help='Number of fake users to create'
        )

    def handle(self, *args, **options):
        self.stdout.write(self.style.WARNING('Starting database population...'))
        create_data(options['total'])
        self.stdout.write(self.style.SUCCESS('Population command executed successfully!'))
