# Generated by Django 5.2.8 on 2025-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycling',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed')], db_column='STATUS', default='ACTIVE', max_length=255),
        ),
    ]
