"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secret Key
try:
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
except KeyError:
    raise RuntimeError("DJANGO_SECRET_KEY is not defined.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Default HTTP port (80 = no need to append “:80”)
HTTP_PORT = os.getenv("HTTP_PORT", "80")

# Hosts defined in .env (Traefik/Frontend/Backend routing)
ENV_HOSTS = {
    "WEB_HOST": os.getenv("WEB_HOST"),
    "ADMIN_HOST": os.getenv("ADMIN_HOST"),
    "ECOPONTO_HOST": os.getenv("ECOPONTO_HOST"),
    "API_HOST": os.getenv("API_HOST"),
    "AUTH_HOST": os.getenv("AUTH_HOST"),
}

def make_origin(host: str | None):
    """
    Converts a hostname into a full origin URL.
    Handles ports automatically:
    - If the HTTP_PORT is 80 → no port is appended
    - Otherwise → :<port> is added 
    """
    if not host:
        return None

    if HTTP_PORT == "80":
        return f"http://{host}"
    
    return f"http://{host}:{HTTP_PORT}"

# Build Docker-based origins (only existing hosts)
DOCKER_ORIGINS = [make_origin(h) for h in ENV_HOSTS.values() if make_origin(h)]

# Allowed Hosts
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
] + [h for h in ENV_HOSTS.values() if h]

# ------------------------------
# CORS Configuration
# ------------------------------

# Local development origins
LOCAL_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOWED_ORIGINS = LOCAL_ORIGINS + DOCKER_ORIGINS
CORS_ALLOW_CREDENTIALS = True

# ------------------------------
# CSRF Configuration
# ------------------------------

# Trusted origins must match the frontend origins exactly
CSRF_TRUSTED_ORIGINS = LOCAL_ORIGINS + DOCKER_ORIGINS

# Allow frontend to read CSRF cookies
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False        # Disabled for HTTP development
CSRF_COOKIE_SAMESITE = "Lax"

# ------------------------------
# Media Files
# ------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ------------------------------
# Applications
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'core.infrastructure',
    'core.domain',
]

# ------------------------------
# Middleware
# ------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ------------------------------
# Templates
# ------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ------------------------------
# Database
# ------------------------------
MIGRATION_MODULES = {
    "domain": "core.infrastructure.migrations",
    "infrastructure": None,
}

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

AUTH_USER_MODEL = 'domain.User'

# ------------------------------
# REST Framework & JWT
# ------------------------------
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.domain.entities.authentication.CustomJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ]
}

SIMPLE_JWT = {
    "USER_ID_FIELD": "user_id"
}

# ------------------------------
# Internationalization
# ------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------
# Static Files
# ------------------------------
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------
# Logging
# ------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'custom_simple': {
            'format': '[%(levelname)s] %(message)s'
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'custom_simple',
        },
    },

    'loggers': {
        # Root logger
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        # Specific logger example
        'core.infrastructure.management.commands.populate_initial_data': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
