# Generated by Django 5.2.8 on 2025-11-22 03:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='defaultusername', max_length=150, unique=True)),
                ('password', models.CharField(default='defaultpassword', max_length=128)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('access_level', models.CharField(choices=[('U', 'Regular User'), ('A', 'Administrator'), ('M', 'Recycling Point Manager')], db_column='ACCESS_LEVEL', default='U', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'USER',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_type', models.CharField(choices=[('PERCENTAGE_DISCOUNT', 'Discount Percentage'), ('DIRECT_DISCOUNT', 'Discount in Cash'), ('GIFT', 'Gift')], db_column='COUPON_TYPE', default='PERCENTAGE_DISCOUNT', max_length=255)),
                ('value', models.IntegerField()),
                ('points_cost', models.IntegerField()),
                ('validation_hash', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('expiring_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'db_table': 'COUPON',
            },
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Partner company',
                'verbose_name_plural': 'Partner companies',
                'db_table': 'PARTNER_COMPANY',
            },
        ),
        migrations.CreateModel(
            name='RecyclingValue',
            fields=[
                ('recycling_value_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points_value', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recycling value',
                'verbose_name_plural': 'Recycling values',
                'db_table': 'RECYCLING_VALUE',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user_id', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='WALLET_USER', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points_balance', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User wallet',
                'verbose_name_plural': 'Users wallet',
                'db_table': 'WALLET',
            },
        ),
        migrations.CreateModel(
            name='CouponsTransactions',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points_value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coupon_id', models.ForeignKey(db_column='COUPON_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupon', to='domain.coupon')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupon_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon transaction',
                'verbose_name_plural': 'coupon transactions',
                'db_table': 'COUPONS_TRANSACTIONS',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='partner_company_id',
            field=models.ForeignKey(db_column='PARTNER_COMPANY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_company', to='domain.partnercompany'),
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edition_date', models.DateTimeField(auto_now=True)),
                ('author_id', models.ForeignKey(db_column='AUTHOR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'POST_BLOG',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='domain.postblog')),
            ],
            options={
                'verbose_name': 'post_image',
                'verbose_name_plural': 'post_images',
                'db_table': 'POST_IMAGE',
            },
        ),
        migrations.CreateModel(
            name='RecyclingPoint',
            fields=[
                ('recycling_point_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user_id', models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recycling point',
                'verbose_name_plural': 'Recycling points',
                'db_table': 'RECYCLING_POINT',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='fav_recycling_point_id',
            field=models.ForeignKey(blank=True, db_column='FAV_RECYCLING_POINT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_recycling_point', to='domain.recyclingpoint'),
        ),
        migrations.CreateModel(
            name='Recycling',
            fields=[
                ('recycling_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points_value', models.IntegerField()),
                ('weight', models.FloatField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('validation_hash', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recycling', to=settings.AUTH_USER_MODEL)),
                ('recycling_point_id', models.ForeignKey(db_column='RECYCLING_POINT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_point', to='domain.recyclingpoint')),
                ('recycling_value_id', models.ForeignKey(db_column='RECYCLING_VALUE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_value', to='domain.recyclingvalue')),
            ],
            options={
                'verbose_name': 'Recycling',
                'verbose_name_plural': 'Recyclings',
                'db_table': 'RECYCLING',
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('RECYCLING', 'Recycling'), ('COUPON_TRANSACTION', 'Bought coupon'), ('EARN_POINTS', 'Earned points')], db_column='operation', default='RECYCLING', max_length=255)),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='WALLET_HISTORY_USER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet history',
                'verbose_name_plural': 'Wallet history',
                'db_table': 'WALLET_HISTORY',
            },
        ),
    ]
