# Generated by Django 5.2.8 on 2025-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recyclingpoint',
            name='recycling_point_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
