# Generated by Django 5.2.8 on 2025-11-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recyclingpoint',
            name='maps_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
