# Generated by Django 5.2.8 on 2025-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_recyclingpoint_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='maps_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recyclingpoint',
            name='recycling_point_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
