# Generated by Django 5.2.8 on 2025-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_create_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
