# Generated by Django 5.2.8 on 2025-11-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_recyclingpoint_maps_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingpoint',
            name='address',
        ),
    ]
