# Generated by Django 5.2.8 on 2025-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_remove_recyclingpoint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
